# Generated by Django 3.2.7 on 2021-12-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dsc',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
